### ISSUE TITLE
Enable `ESPNow.peers_table` for esp8266

### ISSUE THREAD

**Issue by AmirHmZz** [glenn20/micropython#13]
According to [docs](https://micropython-glenn20.readthedocs.io/en/latest/library/espnow.html#wifi-signal-strength-rssi-esp32-only) :

> This feature is not available on ESP8266 devices.

I would be glad to know the reason. I can guess two of the reasons : 
1. Saving RAM
2. Reducing code size

In one of my projects, I need a mechanism to detect the incoming messages' RSSI  on esp8266. Is there anyway that I might achieve this goal?

**Comment by glenn20** [comment]
Those are definitely valid reasons, but the real reason and show-stopper is that the technique I use to extract the RSSI value from the wifi headers comes from a [code fragment from Espressif](https://github.com/espressif/esp-now/blob/4861bdcccb3d1782d0ac695192af040b2888bb55/src/espnow/src/espnow.c#L181) that is only available in the IDF (which does not yet - and may never - support the esp8266). It was necessary to know the exact size of the espnow frame header so we can skip back over that to locate the rssi value in the wifi_pkt_rx_ctrl_t header.

I did some experiments to see if I could blindly fumble around the wifi packet headers on the esp8266 to locate something that looked like the rssi values but had no success. If anyone has more knowledge on the structure of the wifi headers in the esp8266 and can poihnt me to the right location, it might be possible to overcome the other issues mentioned above.
