### ISSUE TITLE
Developing ESP-NOW for circuitpython 

### ISSUE THREAD

**Issue by americoperez49** [glenn20/micropython#4]
Hi Glenn, I wasn't sure how else to get a hold of you so sorry for the "issue".

I am interested in integrating ESP-NOW with CircuitPython but I have no idea where to start. 

Would you be interested in helping me get started/maybe coach me a little so I can attempt this?

**Comment by glenn20** [comment]
@americoperez49  Sorry for the slow response - I've been on holiday for the last week. I know little about circuitpython - especially in the C layer, but I'm happy to help out with this. I _imagine_ it would not be too painful ;).

Do you have a good understanding of the circuitpython internals?

Based on the little that I do know, I believe there is strong compatibility at the C layer (types, etc.) but differences in driver implementations. The esp-now module does lean on the WLAN class implementation and may be sensitive to differences or divergences there.

**Comment by americoperez49** [comment]
Hi Glen,

Not a problem. Hopefully your holidays are going well ☺️.

Honestly, my knowledge of the lower level implemention of circuitpython is
next to none. With that said, I've been programming for a long time now and
I'm sure that whatever I find I'll be able to figure out either on my own
or by asking the circuitpython devs directly.

**Comment by glenn20** [comment]
OK - I'm sure we can figure it out with some help :-). I'm just trawling around the circuitpython repo now, familiarising myself with the layout and interfaces.

**Comment by americoperez49** [comment]
Ya I'm looking through it now as well. I 'll definitely need some help with
understanding some of these things since I'm completely new to this. If you
have any tips on where I should start, please let me know.
